### PR TITLE
Add support for oqee.tv

### PR DESCRIPTION
**Pull request by Psyquoquack**
Oqee is a french isp livetv and vod service.
Thx for the project btw ;)

### CODE REVIEW

**Comment by FoxRefire** [comment]
Thank you!

**Comment by FoxRefire** [comment]
Can you please describe the URL pattern of license server?
By defining URL patterns in [selectRules.conf](https://github.com/FoxRefire/wvg/blob/next/selectRules.conf), right scripts can be automatically selected.

**Comment by Psyquoquack** [comment]
Okay, will do that in a sec.

Unrelated idea: I was thinking of making a N_m3u8DL-RE command maker, like getting the mpd file url, base url, save name (title of page ???), better sub support, etc... Maybe a good idea only for a "fork" and not the original project ? Your thoughts ?

**Comment by Psyquoquack** [comment]
Hey, the license url is a bit weird, the "movie id " then widevine:
https://api.oqee.net/api/v1/avod/license/7y2xxx0ZID12Vzwl/widevine
Maybe add support for regex ? To add a wildcard instead of the gibberish

**Comment by FoxRefire** [comment]
> https://api.oqee.net/api/v1/avod/license/7y2xxx0ZID12Vzwl/widevine

Thank you! added in 51d9503.
The latest commit should now auto-select correctly

> Unrelated idea: I was thinking of making a N_m3u8DL-RE command maker, like getting the mpd file url, base url, save name (title of page ???), better sub support, etc... Maybe a good idea only for a "fork" and not the original project ? Your thoughts ?

I have no plans to add such a feature to this project itself as my country is hypersensitive to copyright laws and I do not want to take any legal risks.
However, this project is free and open source, thus **allowed to modify, fork and redistribute** it as long as you comply with the [license](https://github.com/FoxRefire/wvg/blob/next/LICENSE).
I’ｍ not aware of any recognition how people use this tool.

**Comment by Psyquoquack** [comment]
Cool, thx for the commit !
Wow, I just realized I have the luck of being in a lax country on copyright. But whatever **idk what purpose could serve this tool** `¯\_(0_0)_/¯`
I will only commit my fork and pull request if I think it correspond to the idea of the project :)

**Pull request merged**
