### PR TITLE
Major redesign for GUI / Logic

### PR DESCRIPTION
**Pull request by TPD94**
- background.js: Added better body detail handling in background.js -- during handling of loadBody in pre.py, it simply passes the base64 licBody in an appropriate format for better/modular license handling
- popup.html: Clarified sections on popup.html, renamed widevine guesser to widevine decrypter, renamed divs to be more obvious, created more divs for flex, removed untested schemes with new format. better formatting, removed old services not compatible with new schema.
- popup.js: Adjusted for flex, added else statement for no eme
- popup_drawList.js: Removed arbitrary data, adjusted for flex, adjusted search
- popoup_showHistory.js: Adjusted names, adjusted for flex
- updateNotice.js: adjusted for flex
- pre.py: loadBody now simply returns the whole licBody, Challenge and licHeader loading has been moved to be more script schema specific.
- Amazon.py: Added conformed support for Amazon -- If using None Chrome L3, user must be using Linux / Firefox or use a User-Agent Switcher to switch to it.
- Crunchyroll.py: Added conformed support for crunchyroll
- PolSatBoxGo.py: Added conformed support for PolSatBoxGo
- YouTube.py: Added YouTube support conformed to the new standard.
- slectRules.conf: Need to add comments or proper reasoning for select rules, else specific service.
- style.css: Switched to flex, fixed issue with buttons becoming resized, fixed issue with window expanding in history.

### CODE REVIEW

**Comment by FoxRefire** [comment]
Hello, thanks for PR.
Please check the following matter and correct as necessary.
Also, I've labeled this pull request as `hacktoberfest-accepted`, so if you're registered with [Hacktoberfest](https://hacktoberfest.com/) as  it will count as a contribution.

**Review by FoxRefire — CHANGES_REQUESTED** [review]
What is advantages of decoding base64-encoded requestBody on scheme side?
The reason this is encoded in Base64 is to avoid type errors when passing data between scripts (content-->background-->popup-->pyodide).

References:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities#data_cloning_algorithm
https://pyodide.org/en/stable/usage/type-conversions.html#type-translations

Therefore, I don't think there is any value in directly using license server specific processing.
To avoid code redundancy due to processing that needs to be written in common for all such schemes, the common parts were moved to pre.py in commit 64b86a1.
If additional processing is required, you can get the raw request body by specifying `"blob"` to the `loadbody()` function.

**Review by FoxRefire — CHANGES_REQUESTED** [review]
If you need to set service certificate, define the function like this in pre.py to avoid redundant scheme-side expressions:
```python
def getChallenge(getAs, *cert):
    global session_id
    global pssh

    if bool(cert):
        cdm.set_service_certificate(session_id, cert[0])

    challenge = cdm.get_license_challenge(session_id, pssh)

    match getAs:
        case "blob": pass
        case "b64": challenge = base64.b64encode(challenge).decode()
        case "list": challenge = list(challenge)
    return challenge
```
Also, the `CAUSxwUK...ReuHpfQ=` certificate used in the YouTube and Polsat schemes can be obtained using `Cdm.common_privacy_cert`.

**Review by FoxRefire — CHANGES_REQUESTED** [review]
Is it okay if the JSON used in Telia.py is static?
If the `AccountName` or `PortalId` values ​​change depending on the logged-in user or other conditions, you need to dynamically update the values ​​loaded by `loadBody("json")` rather than setting them statically.

**Comment by TPD94** [comment]
Thanks for your feedback, will adjust and clean up some more with these things in mind.

**Comment by TPD94** [comment]
Reverted some things you mentioned, retained the good things. 

Sorry about the original confusion, after your suggestions it was easier to conform to the code standard!

**Comment by TPD94** [comment]
Last of my commits for today, I believe all these comply with your suggested standards.

**Pull request merged**
